import os

class Config:
    PINECONE_API_KEY = os.getenv('PINECONE_API_KEY', "pcsk_77BFmL_KGUSpB11n15Mj6EodPPaUEBATfvnfGTDt5djVeqgGdTkv1YBbVLziZz3oEhg5Db")
    PINECONE_INDEX_NAME = "mementoai"
    EMBEDDING_MODEL_NAME = 'all-MiniLM-L6-v2'
    EMBEDDING_DIMENSION = 384
    NUM_COMMITS_TO_EXTRACT_FOR_INDEXING = 5000
    MAX_DIFF_CHARS_FOR_STORAGE = 5000
    MAX_DIFF_CHARS_FOR_LLM = 2000
    GEMINI_MODEL_NAME = "gemini-1.5-flash-latest"
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
    GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "AIzaSyCl21GaVEZuD3kfhZjJ-axQ6SQj-Y5PFgc")